hmrc/advance-valuation-rulings

- app/uk/gov/hmrc/advancevaluationrulings/connectors/HttpReaderWrapper.scala
This adds a couple of debug logs to aid debugging during integration in QA
> ARS-483: Add debug logs

- app/uk/gov/hmrc/advancevaluationrulings/config/Module.scala
- app/uk/gov/hmrc/advancevaluationrulings/controllers/ValuationCaseController.scala
- app/uk/gov/hmrc/advancevaluationrulings/repositories/ValuationCaseRepository.scala
- app/uk/gov/hmrc/advancevaluationrulings/services/ValuationCaseService.scala
- conf/app.routes
- conf/application.conf
Currently all cases are returned . That will be refined later
> ARS 151 open case find

- README.md
This just updates the readme so the new config changes made at https://github.com/hmrc/app-config-qa/pull/17642 can be picked up.
> ARS-483: Update readme

- build.sbt
- conf/application.conf
Related to: https://github.com/hmrc/service-manager-config/pull/5102
> Update Server & Integration Framework ports

- app/uk/gov/hmrc/advancevaluationrulings/connectors/DefaultETMPConnector.scala
- app/uk/gov/hmrc/advancevaluationrulings/logging/RequestAwareLogger.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/common/HeaderNames.scala
This fixes the date format in the headers sent to ETMP.
> ARS-483: Fix date format

- app/uk/gov/hmrc/advancevaluationrulings/repositories/ValuationCaseRepository.scala
- build.sbt
- it/uk/gov/hmrc/advancevaluationrulings/repositories/ValuationCaseRepositorySpec.scala
- it/uk/gov/hmrc/advancevaluationrulings/utils/BaseIntegrationSpec.scala
- test-utils/generators/CaseManagementGenerators.scala
- ATP-152 Fix bug with status transition to Open
- Increase coverage
- Remove unneeded actor system
> ATP 152 Fix bug with status transition when assigning

- app/testOnly/TestOnlyController.scala
This fix will make the case show up in the list, e.g.
> Change case status to NEW so that it will show up as a Gateway case

- app/uk/gov/hmrc/advancevaluationrulings/controllers/ApplicationController.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/Application.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationId.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationRequest.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationSubmissionResponse.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationSummary.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationSummaryRequest.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationSummaryResponse.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/EORIDetails.scala
- build.sbt
- conf/app.routes
- test-utils/generators/ModelGenerators.scala
- test/uk/gov/hmrc/advancevaluationrulings/controllers/ApplicationControllerSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationIdSpec.scala
This PR adds the skeleton of endpoints to submit applications, get summaries, or get an application.
The models themselves are just placeholders.
> Application endpoints

- app/uk/gov/hmrc/advancevaluationrulings/views/AttachmentLine.scala.xml
> fix: text-align class removed

- .github/pull_request_template.md
- .gitignore
Jira link: [ARSSTB-151 Set up gitHub PR description template](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-151)
The idea of this ticket is to provide a template for PR descriptions. After merging this branch, anytime someone creates a pull request, the PR description will be pre-populated from the new template.
See the official GitHub guide for more information on how it works:
[Creating a pull request template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository)
[Basic writing and formatting syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
_N / A_
> ARSSTB-151 Added a PR template for GitHub

- .gitignore
- app/uk/gov/hmrc/advancevaluationrulings/config/Module.scala
- app/uk/gov/hmrc/advancevaluationrulings/connectors/DmsSubmissionConnector.scala
- app/uk/gov/hmrc/advancevaluationrulings/controllers/ApplicationController.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/Application.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationRequest.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/WhatIsYourRole.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/WhatIsYourRoleResponse.scala
- app/uk/gov/hmrc/advancevaluationrulings/services/ApplicationService.scala
- app/uk/gov/hmrc/advancevaluationrulings/services/DmsSubmissionService.scala
- it/uk/gov/hmrc/advancevaluationrulings/repositories/ApplicationRepositorySpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/controllers/ApplicationControllerSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationRequestSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/ApplicationServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/AuditServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/DmsSubmissionServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/FopServiceSpec.scala
- [ X] Breaking change
Add what is your role. Mandatory field in request, optional in response to allow support for existing submitted applications where this field is not populated in Mongo
> Arsstb 478

- .gitignore
_Provide a short description of the change. For example: what parts of the code changed, is there any new behaviour...etc._
> added empty file to ensure applications folder is in repo

- app/uk/gov/hmrc/advancevaluationrulings/services/DmsSubmissionService.scala
_Provide a short description of the change. For example: what parts of the code changed, is there any new behaviour...etc._
> Catch file write failures

- app/uk/gov/hmrc/advancevaluationrulings/services/DmsSubmissionService.scala
_Provide a short description of the change. For example: what parts of the code changed, is there any new behaviour...etc._
> Change exception handling to just eat exception rather than bubbling up

- app/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationRequest.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/ContactDetails.scala
- it/uk/gov/hmrc/advancevaluationrulings/repositories/ApplicationRepositorySpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/controllers/ApplicationControllerSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationRequestSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/ApplicationServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/AuditServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/DmsSubmissionServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/FopServiceSpec.scala
This adds in an optional loa to the Application request and an option companyName into the contact details object
> Added in extra field to contact details and added in loa

- app/uk/gov/hmrc/advancevaluationrulings/views/TraderDetail.scala.xml
Jira link: [Agent for trader journey - add agent's company name to the application pdf](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-506)
Added the company name to the application WHEN the user is an agent representing a trader.
> Added the missing agent company name

- app/uk/gov/hmrc/advancevaluationrulings/views/AgentInfo.scala.xml
- app/uk/gov/hmrc/advancevaluationrulings/views/ApplicationSummary.scala.xml
- app/uk/gov/hmrc/advancevaluationrulings/views/DescribeRoleForAgentRoles.scala.xml
- app/uk/gov/hmrc/advancevaluationrulings/views/TraderInfo.scala.xml
- conf/messages
Jira link: [PDF to DMS/caseworkers - Agent for trader should be split in agent and applicant details section](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-515)
Split the agent and trader details apart
> ARSSTB-515 added new views to support agent for trader pdf generation

- app/uk/gov/hmrc/advancevaluationrulings/models/application/Attachment.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/TraderDetail.scala
- it/uk/gov/hmrc/advancevaluationrulings/repositories/ApplicationRepositorySpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/controllers/ApplicationControllerSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationRequestSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/ApplicationServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/AuditServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/DmsSubmissionServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/FopServiceSpec.scala
- [X ] Non-breaking change
Added in an Optional isPrivate to trader details in the Application and ApplicationRequest
> Added optional isPrivate to trader details

- project/AppDependencies.scala
Just the version number needed changing here
> Updated hmrc-mongo-play-28

- conf/application.conf
- [ X] Non-breaking change
Removed modules that are provided by bootstrap
> Removed modules provided by bootstrap

- conf/application.conf
Removed duplicated metrics. See JIRA ticket for list and where there the metric is duplicated.
> Removed duplicated metrics

- project/AppDependencies.scala
Just the version update needed
> Updated object-store-client-play-28

- project/AppDependencies.scala
- [X ] Non-breaking change
Just needed to update version number
> Updated bootstrap-backend-play-28

- app/uk/gov/hmrc/advancevaluationrulings/models/application/GoodsDetails.scala
- app/uk/gov/hmrc/advancevaluationrulings/services/ApplicationService.scala
- app/uk/gov/hmrc/advancevaluationrulings/views/GoodsDetails.scala.xml
- conf/messages
- it/uk/gov/hmrc/advancevaluationrulings/repositories/ApplicationRepositorySpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/controllers/ApplicationControllerSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/models/application/ApplicationRequestSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/ApplicationServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/AuditServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/DmsSubmissionServiceSpec.scala
- test/uk/gov/hmrc/advancevaluationrulings/services/FopServiceSpec.scala
Jira link: [PDFs for 309 and 310 questions ](https://jira.tools.tax.service.gov.uk/browse/ARSSTB-473)
Added info from 309 and 310 to pdfs
> Arsstb 473

- conf/application.conf
The auditing key section is now provided by Bootstrap so have removed it
> Removed auditing key block since provided by Bootstrap

- project/plugins.sbt
Just had to update version number here
> Updated sbt-plugin

- app/uk/gov/hmrc/advancevaluationrulings/connectors/DmsSubmissionConnector.scala
- app/uk/gov/hmrc/advancevaluationrulings/controllers/UserAnswersInternalController.scala
- app/uk/gov/hmrc/advancevaluationrulings/models/application/Attachment.scala
- app/uk/gov/hmrc/advancevaluationrulings/repositories/CounterRepository.scala
- app/uk/gov/hmrc/advancevaluationrulings/services/DmsSubmissionService.scala
> Tidied up a few unused imports and other compiler warnings

- project/AppDependencies.scala
- project/plugins.sbt
[info]   |     +-commons-io:commons-io:2.11.0 (evicted by: 2.18.0)
[info]   |     +-commons-io:commons-io:2.18.0
> DDCE-6249 - Fix commons-io vulnerability(fop)

- app/uk/gov/hmrc/advancevaluationrulings/connectors/DmsSubmissionConnector.scala
- app/uk/gov/hmrc/advancevaluationrulings/services/FopService.scala
- project/AppDependencies.scala
- project/plugins.sbt
DDCE-6298 AVR - advance-valuation-rulings: Remove commons-io Dependency
> DDCE-6298 AVR - advance-valuation-rulings: Remove commons-io Dependency

- project/AppDependencies.scala
- project/plugins.sbt
DDCE-6439 AVR - Address vulnerability warnings relating to commons-io
> DDCE-6439 AVR - Address vulnerability warnings relating to commons-io
